### ISSUE TITLE
Features to improve project

### ISSUE THREAD

**Issue by paucaro** [scalability4all/voice-enabled-chatbot#25]
**Is your feature request related to a problem? Please describe.**
1. When the project is executed, files like .pyc are created, that need to be ignored when uploading to git.
2. Python2 has been updated to python 3, and when running the project with python 3 they give few errors.
3. README file should say how to complete Google API KEY and Weather API KEY
4. The command 'tell me a joke' is not working and give an error NameError: name 'jokes' is not defined

**Describe the solution you'd like**
1. Add a .gitignore file and venv for virtual environments
2. Migrate to Python 3, there are a few differences like the method raw_input.
3. Modify the README file.
4. Modify joke feature

I would like to improve it.

**Comment by satyammittal** [comment]
:+1: For putting up issue. I have assigned you and would love to see how you are going to solve these.
