### ISSUE TITLE
[BUG] FIX pep8 conflicts

### ISSUE THREAD

**Issue by satyammittal** [scalability4all/voice-enabled-chatbot#6]
python files are not yet written clean. I want it to support pep8.

A PR doing it is appreciated.

**Comment by tush05tgsingh** [comment]
hey, @satyammittal  I would like to try this issue as my first contribution.  How do you propose i approach it

**Comment by satyammittal** [comment]
Hi @tush05tgsingh , I will suggest to follow these steps:

a) Install pep8 and read about its usage using https://pypi.org/project/pep8/.
b) Read about pep8 in https://pymbook.readthedocs.io/en/latest/pep8.html.
c) Try to run pep8 on our code.

Hint: There is a tool that automatically formats Python code to conform to the PEP 8 style guide.
